#!/usr/bin/python

import sys
import numpy as np
from matplotlib import pyplot as pl
import argparse
import json
import os

description = 'Utility to plot a binned series of timestamps. X axis values are given in seconds'
parser = argparse.ArgumentParser(description=description)
parser.add_argument('input', metavar='FILE', type=argparse.FileType('r'),
                    help='Input timestamp data')
parser.add_argument('nbins', metavar='N', type=int, help='Number of bins')
args = parser.parse_args()

meta_name = '%s.meta' % args.input.name
params = {}
if os.path.isfile(meta_name):
        params = json.load(open(meta_name))

jiffy = 1.0 / params.get('clockrate', 1)
if args.input.name.endswith('.timetag'):
        from photon_tools.timetag_parse import get_strobe_events
        times = get_strobe_events(args.input.name, 0)
else:
        times = np.fromfile(args.input, np.uint64) * jiffy
pl.hist(times, args.nbins, histtype='step')
pl.show()

