#!/usr/bin/python

import sys
import numpy as np
from matplotlib import pyplot as pl
import argparse
import json

description = 'Utility to plot a binned series of timestamps. X axis values are given in seconds'
parser = argparse.ArgumentParser(description=description)
parser.add_argument('input', metavar='FILE', type=argparse.FileType('r'),
                    help='Input timestamp data')
parser.add_argument('nbins', metavar='N', type=int, help='Number of bins')
args = parser.parse_args()

params = json.decode(args.input + '.params')
jiffy = 1.0 / params['clockrate']
times = np.fromfile(args.input, np.uint64) * jiffy
pl.hist(times, args.nbins, histtype='step')
pl.show()

