#!/usr/bin/python

import sys
from matplotlib import pyplot as pl
import numpy as np

if len(sys.argv) < 4 or '-h' in sys.argv or '--help' in sys.argv:
        print "Usage: %s [input-file] [start-time] [end-time]" % sys.argv[0]
        print 
        print "Utility to remove a range of times from a timestamp file."
        print "Times are given in seconds"
        sys.exit(0)

jiffy = 1e-7
times = np.fromfile(sys.argv[1], np.uint64)
start = float(sys.argv[2]) / jiffy
end = float(sys.argv[3]) / jiffy

# Remove points
take = np.nonzero((times < start) | (times > end))
times = times[take]
# Subtract offset
times[np.nonzero(times > end)] -= end - start

times.tofile(sys.argv[1] + '.new')

