#!/usr/bin/python

import sys
import numpy as np

if len(sys.argv) < 3 or '-h' in sys.argv or '--help' in sys.argv:
        print "Usage: %s [input-file] ..." % sys.argv[0]
        print 
        print "Utility to splice a set of timestamp files."
        sys.exit(0)

jiffy = 4e-12
files = []
offset = 0
for f in sys.argv:
        d = np.fromfile(f, np.uint64)
        d += offset
        offset = d[-1] - offset
        files.append(d)

times = np.hstack(files)
times.tofile(sys.argv[1] + '.new')

