PROGS += picoharp/dump_pt2 picoharp/extract_pt2_timestamps picoharp/dump_pt3
OBJS = picoharp/pt2.o picoharp/pt3.o picoharp/picoharp.o

picoharp/dump_pt2 : $(OBJS)
picoharp/dump_pt3 : $(OBJS)
picoharp/extract_pt2_timestamps : $(OBJS)

